SHBM/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shbm_api.urls')),
]

shbm_api/urls.py
from django.contrib import admin
from django.urls import path, re_path
from django.conf.urls import include
from . import views
from django.views.generic import TemplateView
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from SHBM import settings

urlpatterns = [
    path('hosts/create/', views.CreateHost.as_view(), name='CreateHost'),

	re_path(r'^hosts/delete/(?P<pk>........-....-....-....-............+)$', views.DeleteHost.as_view(), name='DeleteHost'),
    re_path(r'^heartbeat/(?P<pk>........-....-....-....-............+)$',
        views.HeartBeat.as_view(),
        name='HeartBeat'
    ),
    re_path(r'^hosts/(?P<pk>........-....-....-....-............+)$',
        views.EditHost.as_view(),
        name='EditHost'
    ),
    path('hosts/', views.Hosts.as_view(), name='Hosts'),
    path('signup/', views.SignUp.as_view(), name='SignUp'),
    path('logout/', views.Logout.as_view(), name='Logout'),
    path('login/', views.Login.as_view(), name='Login'),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    # path('signup/',
    #     views.signup.as_view(),
    #     name='signup'),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

shbm_api/models.py
from django.db import models
from django import forms
from uuid import uuid4
from time import time

class host(models.Model):
    owner = models.ForeignKey('auth.User', related_name='host', on_delete=models.CASCADE)
    active = models.BooleanField(default=True)
    idstr = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    hostname = models.CharField(max_length=60, default='')
    heartrate = models.BigIntegerField(default=time(), editable=False)
    down = models.BooleanField(default=True, editable=False)
    ip = models.CharField(max_length=60, default='No IP yet', editable=False)
    recipient1 = models.EmailField(default="", verbose_name = "Email to")
    recipient2 = models.EmailField(default="", verbose_name = "Email to (CC)", blank=True)

    def __str__(self):
        return str(self.idstr)

shbm_api/views.py
from django.shortcuts import render
from rest_framework.generics import RetrieveUpdateDestroyAPIView
from rest_framework.response import Response
from rest_framework import status
from django.http import Http404
from .models import host
from .serializers import hostserializer
from time import time
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, LogoutView
class HeartBeat(RetrieveUpdateDestroyAPIView):
    http_method_names = ['get']

    def get_queryset(self, pk):
        try:
            req = host.objects.get(pk=pk)
        except host.DoesNotExist:
            raise Http404("No host matches this ID")
        return req

    def get(self, request, pk):
        try:
            req = self.get_queryset(pk)
        except Http404 as error:
            return Response("404", status=status.HTTP_404_NOT_FOUND)
        req.down = False
        req.heartrate = time()
        req.ip = self.get_client_ip(request)
        req.save(update_fields=['down', 'heartrate', 'ip'])
        return Response("OK", status=status.HTTP_200_OK)

    def get_client_ip(self, request):
        x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if x_forwarded_for:
            ip = x_forwarded_for.split(',')[-1].strip()
        else:
            ip = request.META.get('REMOTE_ADDR')
        return ip


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'signup.html'

class Login(LoginView):
    form_class = AuthenticationForm
    template_name = 'login.html'
    success_url = reverse_lazy('login')

class Logout(LogoutView):
    success_url = reverse_lazy('login')

class Hosts(LoginRequiredMixin, generic.ListView):
    login_url = '/login/'
    def get_queryset(self):
        if not self.request.user.is_authenticated:
            return None
        return host.objects.filter(owner=self.request.user)
    model = host
    template_name = 'hosts.html'  # Specify your own template name/location

class CreateHost(LoginRequiredMixin, generic.CreateView):
    login_url = '/login/'
    model = host
    fields = ["active", "hostname", "recipient1", "recipient2"]
    success_url = "/hosts/"
    template_name = "createhost.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)

class Host(LoginRequiredMixin, generic.DetailView):
    login_url = '/login/'
    model = host
    template_name = 'host.html'

class DeleteHost(LoginRequiredMixin, generic.DeleteView):
    login_url = '/login/'
    model = host
    success_url = "/hosts/"

class EditHost(LoginRequiredMixin, generic.UpdateView):
    login_url = '/login/'
    model = host
    success_url = "/hosts/"
    fields = ["active", "hostname", "recipient1", "recipient2"]
    template_name = 'host.html'



# class createhost(RetrieveUpdateDestroyAPIView):
#     http_method_names = ['post']
#     def post(self,request):
#         serializer = hostserializer(data=request.data)
#         if serializer.is_valid():
#             serializer.save()
#             return Response(serializer.data["idstr"], status=status.HTTP_201_CREATED)
#         return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>wcshamblin</title>
  <!-- Bootstrap core CSS -->
  {% load static %}
  <link rel="stylesheet"  href="{%  static  'vendor/bootstrap/css/bootstrap.min.css'  %}">

</head>


<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>

  <script src="{%  static  'vendor/jquery/jquery.min.js'  %}"></script>
  <script src="{%  static  'vendor/bootstrap/js/bootstrap.bundle.min.js'  %}"></script>

</body>
</html>

templates/createhost.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Create a host{% endblock %}

{% block content %}
  <h2>Create a host</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
  </form>


  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login/">Log in</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endif %}

{% endblock %}

templates/home.html
<!-- templates/home.html-->
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  Would you like to view your <a href="{% url 'Hosts' %}">hosts</a>?
{% else %}
  <p>You cannot create hosts until you are <a href="{% url 'Login' %}">logged in</a>.</p>
  <br>
{% endif %}
  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login/">Log in</a>
          </li>

        </ul>
      </div>
    </div>
  </nav>
{% endif %}
{% endblock %}

templates/host.html
{% extends 'base.html' %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <p><b>IP:</b> {{ host.ip }}</p>
    <p><b>Last ping:</b> {{ host.heartrate }}</p>
    <p><b>Crontab command: </b><code>* * * * * curl domain.com/heartbeat/{{ host.idstr }}</code></p>
    <button type="submit">Save</button>
  </form>

  <br>
  <form action="{% url 'DeleteHost' host.idstr %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete host">
  </form>


  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login/">Log in</a>
          </li>
          
        </ul>
      </div>
    </div>
  </nav>
{% endif %}

{% endblock %}

templates/hosts.html
{% extends 'base.html' %}

{% block content %}
  <h3>Hosts</h3>
  {% if host_list %}
  <ul>
    {% for host in host_list %}
      <li>
	      <a href="/hosts/{{host.idstr}}">{{ host.hostname }}</a> ({{host.ip}})
      </li>
    {% endfor %}
    <br>
    <a href="{% url 'CreateHost' %}">Add another host</a>
  </ul>
  {% else %}
    <p>You have no hosts.</p>
    <a href="{% url 'CreateHost' %}">Create one?</a>
  {% endif %}
  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="/logout/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="/login/">Log in</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endif %}
       
{% endblock %}

templates/login.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
{% block content %}

<h2>Login</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  No account? Create one <a href="/signup/">here</a>.
  <br>
  <button type="submit">Login</button>
</form>


  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="/login/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item active">
	    <a class="nav-link" href="/logout/">Log in</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endif %}

{% endblock %}

templates/signup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}

{% block title %}Sign Up{% endblock %}

{% block content %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign Up</button>
  </form>

  <nav class="navbar navbar-expand-lg navbar-light fixed-bottom">
    <div class="container">
      <a class="navbar-brand" href="/"><span class="text">SHBM</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/hosts">Hosts</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="/logout/">Log out</a>
          </li>

          {% else %}
          <li class="nav-item active">
            <a class="nav-link" href="/login/">Log in</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
{% endif %}

{% endblock %}